---
Scenes:
  - File: Scene.yaml
    Output: DepthOfField.png

# Renderer settings.
Renderer:
  Type: Whitted
  Sampler: Random
  Filter: Box
  Camera Samples: 128
  Ray Depth: 8

Framebuffer:
  Type: 8-bit
  Output: PNG
  Resolution: [ 1000, 1000 ]
