---
Scenes:
  - File: Scene.yaml
    Output: CornellBox.png

# Renderer settings.
Renderer:
  Type: Path
  Sampler: Random
  Filter: Box
  Camera Samples: 128
  Ray Depth: 8

Framebuffer:
  Type: 8-bit
  Output: PNG
  Resolution: [ 1200, 1200 ]
