---
Scene:
  File: Scene.yaml
  Acceleration:
    Type: None

Renderer:
  Type: Whitted
  Env Map Resolution: 256

Framebuffer:
  Type: Simple
  Width: 1920
  Height: 1080

Output:
  Type: PNG
  File: Render.png
