---
Project Name: Cornell Box

Scenes:
  - File: Scene.yaml
    Output: CornellBox.png

Renderer:
  Type: Path
  Sampler: Random
  Filter: Box
  Camera Samples: 16
  Ray Depth: 100

Framebuffer:
  Type: 8-bit
  Output: PNG
  Resolution: [ 1000, 1000 ]
