---
# Name of the project, will be displayed in Cinder while rendering
Project Name: Sample Cinder Project

# A list of scenes to render in the project, with its corresponding output file
Scenes:
  - File: Scene.yaml
    Output: Render.png

# Renderer to use
Renderer:
  Type: Preview
  Sampler: Random
  Filter: Box
  Samples: 8

# Type of framebuffer, and the format of the output.
# Should be the same format as your output file (*.png -> PNG)
Framebuffer:
  Type: 8-bit
  Output: PNG
  Resolution: [ 1920, 1080 ]
