---
Project Name: Cornell Box

Scenes:
  - File: Scene.yaml
    Output: CornellBox.png

Renderer:
  Type: Whitted
  Sampler: Random
  Filter: Box
  Camera Samples: 8
  Ray Depth: 2

Framebuffer:
  Type: 8-bit
  Output: PNG
  Resolution: [ 1000, 1000 ]
