---
# Name of the project, will be displayed in Cinder while rendering
Project Name: Sample Cinder Project

# A list of scenes to render in the project, with its corresponding output file
Scenes:
  - File: Model.yaml
    Output: Model.png

# Renderer to use
Renderer:
  Type: Whitted
  Sampler: Random
  Filter: Box
  Samples: 8
  Ray Depth: 5
  
# Type of framebuffer, and the format of the output.
# Should be the same format as your output file (*.png -> PNG)
Framebuffer:
  Type: 8-bit
  Output: PNG
  Resolution: [ 3840, 2160 ]
