---
Scene:
  File: Scene.yaml
  Acceleration:
    Type: None

Renderer:
  Type: Preview
  Supersample: 1

Framebuffer:
  Type: Simple
  Width: 1920
  Height: 1080

Output:
  Type: PNG
  File: Render.png
